name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    # Build it!
    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/parsec-hpr-docker:latest .
    # Push the Docker image to GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/parsec-hpr-docker:latest
